### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by tjdam**
Hi!

I wish I could contribute with more than this.
Maybe one day :)

Thanks for the great work!

### CODE REVIEW

**Comment by dominique-vassard** [comment]
Hi,
thank you for the PR, I hope too it's your first :)

Sorry if for the moment, the lib is not much moving. My daytime job is very time consuming and I'm not able to work properly on seraph. Hope it will be the case at the start of next year.

**Comment by tjdam** [comment]
It was indeed my first! 🎉

It's looking really neat so far, love how familiar it feels if you are already used to Ecto! Excited to the idea of making Neo4j more approachable to the Elixir ecosystem!
Do you use it in your day job?

Not related, but I have some questions related to some difficulties I've been encountering... would you rather questions be sent here or on Elixir Forum?

**Comment by dominique-vassard** [comment]
Thanks for the kind words.
Making Neo4j available and up to date for Elixir is not an easy and Serpah was the missing part for making really enjoyable.
It's far for being finished but, well something has to be started before being finished :) 

Regarding questions: it depends.
If it seems some lacking features / bugs / etc., just open a issue.
For more general questions, Elixir forum is the way to go I think. There, answers can benefit others.

The saddest thing is that I never used Neo4j with Elixir in my jobs. I've used it with Python, I will (with a bit of luck) use it with PHP (and I will have to develop Bolt V3 support... again but in another language) and for the use cases it address, it's really nice and a pleasure to work with.
So, for Elixir I only use it on a personal project. 

BTW, if you want to see something horrible, check ecto_neo4j :D

**Comment by tjdam** [comment]
Roger that!

I did find ecto_neo4j before I stumbled upon this project! I thought it was a great effort but I couldn't help thinking it was a big struggle trying to make something fit where it didn't haha. I thought something more suited to graph databases should be done but the idea of making it so while maintaining the familiarity with Ecto is genius. I'm so excited with this!

I'm just learning Elixir so for now I'll probably invest some time using Sips, so hopefully I'll be able to contribute with Seraph in the future!

Thanks for your time!

**Pull request merged**
